Django_project2.0/quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('authors/', include('authors_app.urls')),
    path('quotes/', include('quotes_app.urls')),
    path('user/', include('user_app.urls')),
   
]

Django_project2.0/quotes/user_app/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView

from .views import RegisterView, ResetPasswordView

app_name = "user_app"

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='signup'),
    path('signin/', LoginView.as_view(template_name='user_app/login.html'), name='signin'),
    path('logout/', LogoutView.as_view(template_name='user_app/logout.html'), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='user_app/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='user_app/password_reset_confirm.html',
                                          success_url='/user/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='user_app/password_reset_complete.html'),
         name='password_reset_complete'),
]

Django_project2.0/quotes/user_app/models.py
from django.db import models

# Create your models here.

Django_project2.0/quotes/user_app/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, TextInput, EmailInput, EmailField, PasswordInput

class RegisterForm(UserCreationForm):
    username = CharField(max_length=16, min_length=3, required=True, widget=TextInput(attrs={"class": "form-control"}))
    email = EmailField(max_length=25, required=True, widget=EmailInput(attrs={"class": "form-control"}))
    password1 = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))
    password2 = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    username = CharField(max_length=16, min_length=3, required=True, widget=TextInput(attrs={"class": "form-control"}))
    password = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    

Django_project2.0/quotes/user_app/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

from .forms import RegisterForm

# Create your views here.
class RegisterView(View):
    template_name = 'user_app/register.html'
    form_class = RegisterForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="authors_app:all_authors")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f"Congratulations {username}. Your account was succsessfully  created !")
            return redirect(to="user_app:signin")
        return render(request, self.template_name, {"form": form})
    

class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'user_app/password_reset.html'
    email_template_name = 'user_app/password_reset_email.html'
    html_email_template_name = 'user_app/password_reset_email.html'
    success_url = reverse_lazy('user_app:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'user_app/password_reset_subject.txt'

Django_project2.0/quotes/user_app/templates/user_app/login.html
{% extends 'authors_app/base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Login User</h2>

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <span {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</span>
        {% endfor %}
    </div>
    {% endif %}

    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password }}
            </label>
            <span>{{form.errors.password}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
        <div class="small text-center">
            <a href="{% url "user_app:password_reset" %}" class="text-center"><i>Forgot Password?</i></a>
        </div>
    </form>
</div>
{% endblock %}

Django_project2.0/quotes/user_app/templates/user_app/logout.html
{% extends 'authors_app/base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-header bg-primary text-white">
                <h1 class="mb-0">Logout</h1>
            </div>
            <div class="card-body">
                <form method="post" action="{% url 'user_app:signin' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-warning">Login</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

Django_project2.0/quotes/user_app/templates/user_app/password_reset.html
{% extends 'authors_app/base.html' %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

Django_project2.0/quotes/user_app/templates/user_app/password_reset_complete.html
{% extends "authors_app/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

Django_project2.0/quotes/user_app/templates/user_app/password_reset_confirm.html
{% extends "authors_app/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

Django_project2.0/quotes/user_app/templates/user_app/password_reset_done.html
{% extends "authors_app/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

Django_project2.0/quotes/user_app/templates/user_app/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'user_app:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'user_app:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

Django_project2.0/quotes/user_app/templates/user_app/register.html
{% extends 'authors_app/base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Register User</h2>
    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Email
                {{ form.email }}
            </label>
            <span>{{form.errors.email}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password1 }}
            </label>
            <span>{{form.errors.password1}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Repeat Password
                {{ form.password2 }}
            </label>
            <span>{{form.errors.password2}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}