Django_project2.0/quotes/authors_app/urls.py
from rest_framework import routers
from .views import AuthorViewSet
from django.urls import path
from .views import all_authors, add_author, scrape_data_view

router = routers.DefaultRouter()
router.register(r'', AuthorViewSet)

app_name = 'authors_app'
urlpatterns = [
    #path('', include(router.urls)),
    path('add_author/', add_author, name='add_author'),
    path('all_authors/', all_authors, name='all_authors'),
    path('scrape-data/', scrape_data_view, name='scrape_data'),
]

Django_project2.0/quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('authors/', include('authors_app.urls')),
    path('quotes/', include('quotes_app.urls')),
    path('user/', include('user_app.urls')),
   
]

Django_project2.0/quotes/quotes_app/urls.py
# from rest_framework import routers
from django.urls import path
from .views import add_quote, all_quotes, add_tag, author_detail ,TopTagsView, TagQuotesView

app_name = 'quotes_app'
urlpatterns = [
    path('add_quote/', add_quote, name='add_quotes'),
    path('all_quotes/', all_quotes, name='all_quotes'),
    path('top-tags/', TopTagsView.as_view(), name='top_tags'),
    path('add_tag/', add_tag, name='add_tags'),
    path('tag/<str:tag_name>/', TagQuotesView.as_view(), name='tag_quotes'),
    path('author/<str:fullname>/', author_detail, name='author_detail'),
]

Django_project2.0/quotes/user_app/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView

from .views import RegisterView, ResetPasswordView

app_name = "user_app"

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='signup'),
    path('signin/', LoginView.as_view(template_name='user_app/login.html'), name='signin'),
    path('logout/', LogoutView.as_view(template_name='user_app/logout.html'), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='user_app/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='user_app/password_reset_confirm.html',
                                          success_url='/user/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='user_app/password_reset_complete.html'),
         name='password_reset_complete'),
]

Django_project2.0/quotes/authors_app/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length = 100, null=False, unique=True, default='Default Fullname')
    born_date = models.CharField(max_length=50, null=False)
    born_location = models.CharField(max_length=150, null=False)
    description = models.CharField()

    def __str__(self):
        return self.fullname

Django_project2.0/quotes/authors_app/forms.py
#from django.forms import ModelForm, HiddenInput, ModelChoiceField
from django.forms import ModelForm, CharField, Form, TextInput, BooleanField 

from .models import Author


class AuthorForm(ModelForm):
    fullname = CharField(max_length=100, min_length=3,
            widget=TextInput(attrs={"class": "form-control", "id": "exampleInputEmail1"}))
    born_date = CharField(widget=TextInput(attrs={"class": "form-control", "id": "exampleInputEmail"}))
    born_location = CharField(max_length=255, widget=TextInput(attrs={"class": "form-control", "id": "exampleInputLocation"}))
    description = CharField(widget=TextInput(attrs={"class": "form-control", "id": "exampleInputDescription"}))
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class ScrapeDataForm(Form):
    scrape_button = BooleanField(label='Scrape Data', required=False)

Django_project2.0/quotes/authors_app/views.py
# Create your views here.
from rest_framework import viewsets
from .models import Author
from .serializers import AuthorSerializer

from .utils import scrape_data
from django.core.paginator import Paginator
from .forms import AuthorForm, ScrapeDataForm
from quotes_app.forms import Quote
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

class AuthorViewSet(viewsets.ModelViewSet):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer

# --------------------------- ---------------------------
# ---------------------------add a new author ---------------------------
@login_required
def add_author(request):
    print("View is being executed!")
    if request.method == 'POST':
        print(request.POST)
        form = AuthorForm( request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='authors_app:add_author')  # Replace with the actual success URL
    else:
        form = AuthorForm()
    return render(request, 'authors_app/add_author.html', context={"form": form})


# --------------------------- ---------------------------
# ---------------------------show on page all authors ---------------------------
def all_authors(request):
    author = Author.objects.all()
    paginator = Paginator(author, 10)  # Show 10 quotes per page

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'authors_app/all_authors.html', {'page_obj': page_obj})

# --------------------------- ---------------------------
# ---------------------------work with parcing the data and write to json ---------
def scrape_data_view(request):
    if request.method == 'POST':
        form = ScrapeDataForm(request.POST)
        if form.is_valid() and form.cleaned_data['scrape_button']:
            # Виклик функції для скрапінгу даних
            scrape_data()
            return render(request, 'authors_app/success_page.html')
    # Відображення форми на сторінці
    form = ScrapeDataForm()
    return render(request, 'authors_app/scrape_data_page.html', {'form': form})

Django_project2.0/quotes/authors_app/templates/authors_app/add_author.html
<!-- authors_app/templates/authors_app/add_author.html -->

{% extends 'authors_app/base.html' %}

{% block title %}Add Author{% endblock %}

{% block content %}
  <div class="container mt-3">
    {% if form.errors and form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
      </div>
    {% endif %}
    <form action="{% url 'authors_app:add_author' %}" method="post">
      {% csrf_token %}
      <div class="mb-3">
        <label for="id_fullname" class="form-label">Full Name</label>
        {{ form.fullname }}
        <div class="form-text">Full name of the author</div>
        <span>{{ form.errors.fullname }}</span>
      </div>
      <div class="mb-3">
        <label for="id_born_date" class="form-label">Born Date</label>
        {{ form.born_date }}
        <span>{{ form.errors.born_date }}</span>
      </div>
      <div class="mb-3">
        <label for="id_born_location" class="form-label">Born Location</label>
        {{ form.born_location }}
        <span>{{ form.errors.born_location }}</span>
      </div>
      <div class="mb-3">
        <label for="id_description" class="form-label">Description</label>
        {{ form.description }}
        <div class="form-text">Description for the author</div>
        <span>{{ form.errors.description }}</span>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
      <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
  </div>
{% endblock %}

Django_project2.0/quotes/authors_app/templates/authors_app/all_authors.html
<!-- authors_app/templates/authors_app/all_authors.html -->
{% extends 'authors_app/base.html' %}


{% block title %}All Authors{% endblock %}

{% block content %}
{% load static %}
  <link rel="stylesheet" href="{% static 'authors_app/all_authors.css' %}">
  
  <div class="container mt-3">
    <h2>All Authors</h2>
    {% if page_obj %}
    <div class="pagination">
      <span class="step-links">
          {% if page_obj.has_previous %}
              <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-primary">Previous</a>
          {% endif %}
  
          <span class="current" style="color: navy;">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>
  
          {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}" class="btn btn-primary">Next</a>
          {% endif %}
      </span>
  </div>
      {% for author in page_obj %}
        <div class="quote-box">
          <p class="fullname"><strong>{{ author.fullname }}</strong></p>
          <p class="born-date">
            <span class="born-date-label">Born date:</span>
            {{ author.born_date }}
          </p>
          <p class="born-location">
            <span class="born-location-label">Born location:</span>
            {{ author.born_location }}
          </p>
          <p class="description">
            <span class="description-label">Description:</span>
            {{ author.description }}
        </p>
        </div>
      {% endfor %}

    {% else %}
      <p>No quotes available.</p>
    {% endif %}
  </div>
{% endblock %}

Django_project2.0/quotes/authors_app/templates/authors_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Quotes and Authors{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'authors_app/main.css'%}">
    <!-- Add more static files if needed -->
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'authors_app:all_authors' %}">Home</a>
                
                <a class="nav-link" href="{% url 'authors_app:all_authors' %}">Authors</a>
                <form method="post" action="{% url 'user_app:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-link">Logout</button>
                </form>

                <form method="post" action="{% url 'authors_app:scrape_data' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-link">Scrape data</button>
                </form>

                <a class="nav-link" href="{% url 'quotes_app:all_quotes' %}">Quotes</a>
                <a class="nav-link" href="{% url 'quotes_app:add_quotes' %}">Add Quote</a>
                <a class="nav-link" href="{% url 'authors_app:add_author' %}">Add Author</a>
                <a class="nav-link" href="{% url 'quotes_app:add_tags' %}">Add Tag</a>
                <a class="nav-link" href="{% url 'user_app:signin' %}">Login</a>
                <a class="nav-link" href="{% url 'user_app:signup' %}">Signup</a>
            </div>
        </div>
    </div>
</nav>

<div class="container mt-3">
    {% block content %}
    {% endblock %}
</div>

<div class="sidebar">
    <a href="{% url 'quotes_app:top_tags' %}">Top 10 Tags</a>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

Django_project2.0/quotes/authors_app/templates/authors_app/scrape_data_page.html
<!-- templates/scrape_data_page.html -->

<!-- scrape_data_page.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Scrape Data</title>
</head>
<body>
    <h2>Scrape Data</h2>
    <form method="post" action="">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Submit</button>
    </form>
</body>
</html>

Django_project2.0/quotes/authors_app/templates/authors_app/success_page.html
<!-- templates/success_page.html -->

<h2>Data scraped successfully!</h2>