Django_project2.0/quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('authors/', include('authors_app.urls')),
    path('quotes/', include('quotes_app.urls')),
    path('user/', include('user_app.urls')),
   
]

Django_project2.0/quotes/quotes_app/urls.py
# from rest_framework import routers
from django.urls import path
from .views import add_quote, all_quotes, add_tag, author_detail ,TopTagsView, TagQuotesView

app_name = 'quotes_app'
urlpatterns = [
    path('add_quote/', add_quote, name='add_quotes'),
    path('all_quotes/', all_quotes, name='all_quotes'),
    path('top-tags/', TopTagsView.as_view(), name='top_tags'),
    path('add_tag/', add_tag, name='add_tags'),
    path('tag/<str:tag_name>/', TagQuotesView.as_view(), name='tag_quotes'),
    path('author/<str:fullname>/', author_detail, name='author_detail'),
]

Django_project2.0/quotes/quotes_app/models.py
from django.db import models
from authors_app.models import Author

class Tag(models.Model):
    name = models.CharField(max_length=80, unique=True,)
    usage_count = models.IntegerField(default=0)

    def __str__(self):
        return self.name

# Create your models here.
class Quote(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='quotes', blank=False)
    tags = models.ManyToManyField(Tag, blank=False)
    quote = models.CharField(blank=False)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        for tag in self.tags.all():
            tag.usage_count += 1
            tag.save()
            
    def __str__(self):
        return f'{self.quote} - {self.author.fullname}'

Django_project2.0/quotes/quotes_app/forms.py
# forms.py in quotes_app
from django import forms
from .models import Quote, Tag
from authors_app.models import Author

class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={"class": "form-control", "id": "exampleInputTag"}),
        }


class QuoteForm(forms.ModelForm):
    author = forms.ModelChoiceField(queryset=Author.objects.all(), widget=forms.Select(attrs={"class": "form-control", "id": "exampleInputAuthor"}))
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.SelectMultiple(attrs={"class": "form-control", "id": "exampleInputTags"}))
    quote = forms.CharField(max_length=255, widget=forms.TextInput(attrs={"class": "form-control", "id": "exampleInputQuote"}))
    class Meta:
        model = Quote
        fields = ['author', 'tags', 'quote']

Django_project2.0/quotes/quotes_app/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .models import Quote, Tag
from authors_app.views import Author
from .serializers import QouteSerializer

from rest_framework import generics
from django.contrib.auth.models import User
from rest_framework.permissions import AllowAny
from .serializers import UserRegistrationSerializer

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import QuoteForm, TagForm
from django.core.paginator import Paginator

from django.views import View
from django.views.generic import ListView


class UserRegistrationView(generics.CreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserRegistrationSerializer
    permission_classes = [AllowAny]

# Create your views here.
# --------------------------- ---------------------------
# ---------------------------get all quotes ---------------------------
@api_view(['GET'])
def list_quotes(request):
    queryset = Quote.objects.all()
    serializer = QouteSerializer(queryset, many=True)
    return Response(serializer.data)

# --------------------------- ---------------------------
# ---------------------------add new quote ---------------------------
@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            quote = form.save() 
            print("Author:", quote.author)
            
            # add tags
            form.instance.tags.set(form.cleaned_data['tags'])
            
            #print("Tags:", quote.tags.all())
            return redirect(to='quotes_app:add_quotes')  # Redirect to the quotes page or any other desired URL
    else:
        form = QuoteForm()
    return render(request, 'quotes_app/add_quote.html', {'form': form})

# --------------------------- ---------------------------
# ---------------------------add new tag ---------------------------
@login_required
def add_tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save(commit=False)
            tag.save()
            return redirect(to='quotes_app:add_tags')  # Redirect to the quotes page or any other desired URL
    else:
        form = TagForm()
    return render(request, 'quotes_app/add_tags.html', {'form': form})

# --------------------------- ---------------------------
# ---------------------------get 10 quotes to show on page ---------------------------
def all_quotes(request):
    quote = Quote.objects.all()
    paginator = Paginator(quote, 10) 

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'quotes_app/all_quotes.html', {'page_obj': page_obj})

# --------------------------- ---------------------------
# ---------------------------getting some information about author ---------------------------
def author_detail(request, fullname):
    author = get_object_or_404(Author, pk=fullname)
    return render(request, 'quotes_app/author_detail.html', {'author': author})

class TagQuotesView(ListView):
    template_name = 'quotes_app/tag_quotes_list.html'
    context_object_name = 'tag_quotes'

    def get_queryset(self):
        tag_name = self.kwargs['tag_name']
        return Quote.objects.filter(tags__name__iexact=tag_name)

# --------------------------- ---------------------------
# ---------------------------class for getting top 10 tags ---------------------------
class TopTagsView(View):
    template_name = 'quotes_app/top_ten_tags_page.html'

    def get(self, request, *args, **kwargs):
        Tag.objects.all().update(usage_count=0)
        for quote in Quote.objects.all():
            for tag in quote.tags.all():
                tag.usage_count += 1
                tag.save()
        tags = Tag.objects.order_by('-usage_count')[:10]
        return render(request, self.template_name, {'tags': tags})

Django_project2.0/quotes/quotes_app/templates/quotes_app/add_quote.html
<!-- quotes_app/templates/quotes_app/add_quote.html -->

{% extends 'quotes_app/base.html' %}

{% block title %}Add Quote{% endblock %}

{% block content %}
  <div class="container mt-3">
    {% if form.errors and form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
      </div>
    {% endif %}
    <form action="{% url 'quotes_app:add_quotes' %}" method="post">
      {% csrf_token %}
      <div class="mb-3">
        <label for="id_author" class="form-label">Author</label>
        {{ form.author }}
        <div class="form-text">Select the author for the quote</div>
        <span>{{ form.errors.author }}</span>
      </div>
      <div class="mb-3">
        <label for="id_tags" class="form-label">Tags</label>
        {{ form.tags }}
        <div class="form-text">Select tags for the quote</div>
        <span>{{ form.errors.tags }}</span>
      </div>
      <div class="mb-3">
        <label for="id_quote" class="form-label">Quote</label>
        {{ form.quote }}
        <span>{{ form.errors.quote }}</span>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
      <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
  </div>
{% endblock %}

Django_project2.0/quotes/quotes_app/templates/quotes_app/add_tags.html
<!-- quotes_app/templates/quotes_app/add_tag.html -->

{% extends 'authors_app/base.html' %}

{% block title %}Add Tag{% endblock %}

{% block content %}
  <div class="container mt-3">
    {% if form.errors and form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
      </div>
    {% endif %}
    <form action="{% url 'quotes_app:add_tags' %}" method="post">
      {% csrf_token %}
      <div class="mb-3">
        <label for="id_name" class="form-label">Name</label>
        {{ form.name }}
        <div class="form-text">Enter the name for the tag</div>
        <span>{{ form.errors.name }}</span>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
      <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
  </div>
{% endblock %}

Django_project2.0/quotes/quotes_app/templates/quotes_app/all_quotes.html
{% extends 'authors_app/base.html' %}

{% block title %}All Quotes{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'quotes_app/all_quotes.css' %}">

<div class="container mt-3">
    <h2>All Quotes</h2>
    {% if page_obj %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-primary">Previous</a>
            {% endif %}

            <span class="current" style="color: navy;">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="btn btn-primary">Next</a>
            {% endif %}
        </span>
    </div>
    {% for quote in page_obj %}
    <div class="quote-box">
      <p class="author">
        <a href="{% url 'quotes_app:author_detail' quote.author.id %}">
            {{ quote.author.fullname }}
        </a>
      </p>
        <p>{{ quote.quote }}</p>
        <p class="tags">
            <span style="color: green;">Tags:</span>
            {% for tag in quote.tags.all %}
                <a href="{% url 'quotes_app:tag_quotes' tag.name %}">{{ tag.name }}</a>{% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
    </div>
    {% endfor %}

    {% else %}
    <p>No quotes available.</p>
    {% endif %}
</div>
{% endblock %}

Django_project2.0/quotes/quotes_app/templates/quotes_app/author_detail.html
<!-- quotes_app/templates/quotes_app/author_detail.html -->

{% extends 'authors_app/base.html' %}

{% block title %}Author Detail - {{ author.fullname }}{% endblock %}

{% block content %}
    <h1>{{ author.fullname }}</h1>
    <p><strong>Birthdate:</strong> {{ author.born_date }}</p>
    <p><strong>Born Place:</strong> {{ author.born_location }}</p>
    <p><strong>Description:</strong> {{ author.description }}</p>
{% endblock %}

Django_project2.0/quotes/quotes_app/templates/quotes_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Quotes and Authors{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes_app/main.css'%}">
    <!-- Add more static files if needed -->
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'quotes_app:all_quotes' %}">Quotes</a> 
            </div>
        </div>
    </div>
</nav>

<div class="container mt-3">
    {% block content %}
    {% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

Django_project2.0/quotes/quotes_app/templates/quotes_app/tag_quotes_list.html
<!-- tag_quotes_list.html -->

{% extends 'authors_app/base.html' %}

{% block title %}Tag Quotes{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'quotes_app/all_quotes.css' %}">

  <div class="container mt-3">
    <h2>Tag Quotes</h2>
    {% if tag_quotes %}
      {% for quote in tag_quotes %}
        <div class="quote-box">
          <p class="author">{{ quote.author }}</p>
          <p>{{ quote.quote }}</p>
          <p class="tags">
            <span style="color: green;">Tags:</span> 
            {% for tag in quote.tags.all %}
              {{ tag.name }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
          </p>
        </div>
      {% endfor %}
    {% else %}
      <p>No quotes available for this tag.</p>
    {% endif %}
  </div>
{% endblock %}

Django_project2.0/quotes/quotes_app/templates/quotes_app/top_ten_tags_page.html
{% extends 'quotes_app/base.html' %}

{% block title %}Top 10 Tags{% endblock %}

{% block content %}
{% load static %}
    <link rel="stylesheet" href="{% static 'quotes_app/top_ten_tags.css' %}">
    
    <h1>Top 10 Tags</h1>

    <div class="top-ten-tags">
        <ul>
            {% for tag in tags %}
                <li>
                    <a href="{% url 'quotes_app:tag_quotes' tag.name %}">
                        {{ tag.name }} ({{ tag.usage_count }})
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}